### PR TITLE
Update

### PR DESCRIPTION
**Pull request by wapmorgan**
- Add `actionColumnText` and `actionButtonLabel` to `.addGrid()`.
    - Set `actionColumnText` to change default text of action column (by default "Action"). 
    - Set `actionButtonLabel` to change default label of action button (by default "Press").
- Add `defaultValue` to `.textBox()`. Set it to fill entry with initial value.
- Change behavior of `action` argument of `.addGrid()`: now it passes in number of a row instead of row data.
- Add `rows` list to `SimpleGrid` with rows data. Use it to get or change data of grid. Use it in `action`  function to get or update data.

### CODE REVIEW

**Comment by jarvisteach** [comment]
This looks great! But, the changes to `SimpleEntryDialog` are breaking the test suite - the `NumDialog` class also extends the `SimpleEntryDialog` class. Can you look at updating the patch to resolve that?

And then, can you include it in the testing - if you look in `tests/widget_test.py`, there's a function `test_pop_ups()` that tests both of these, can you add in additional tests to test the new parameters?

**Comment by wapmorgan** [comment]
OK, I'll try. And what about other new parameters to grid? I think about text for add row entry button and fixed width for columns

**Comment by wapmorgan** [comment]
Added `addRowButtonLabel` option to grid. It's value is used as button on the add-entry row. Default is `Add`

**Comment by wapmorgan** [comment]
I've added tests.

**Comment by jarvisteach** [comment]
Hey - just to let you know, I'm aware of this, and will look at rolling it in after I've pushed out the next release, things have got a bit busy this end, but I'll be freed up in about a weeks time.

**Pull request merged**
